name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          check-latest: true

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1
        with:
          concurrent: true
          job-id: 'npc-lib-full-build'
          gradle-distribution-sha-256-sum-warning: false

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build check jar
